### ISSUE TITLE
adjust thumbnail display for very wide images

### ISSUE THREAD

**Issue by eroux** [tify-iiif-viewer/tify#136]
In [this example](https://tify.rocks/?manifest=https%3A%2F%2Fiiifpres.bdrc.io%2Fvo%3Abdr%3AI3852%2Fmanifest&tify=%7B%22pan%22%3A%7B%22x%22%3A0.5%2C%22y%22%3A0.089%7D%2C%22view%22%3A%22thumbnails%22%2C%22zoom%22%3A1.387%7D) (using [this manifest](https://iiifpres.bdrc.io/vo:bdr:I3852/manifest)) the thumbnails look like:

![Capture d’écran de 2022-11-06 11-24-26](https://user-images.githubusercontent.com/60868/200165578-21e533f8-61e9-4e57-a459-6a9ac153edac.png)

which is not ideal because most of the display is just grey filler and the actual images are tiny. In [our custom mirador2](https://library.bdrc.io/show/bdr:I3852#open-viewer) it looks like

![Capture d’écran de 2022-11-06 11-26-10](https://user-images.githubusercontent.com/60868/200165641-0256dfd9-b42f-4255-8dcc-efa1b53db758.png)

which is a bit better for that format. Perhaps one way to switch between the two could be to adjust the number of thumbnails per row? For modern books it could be 3 (like it is now in tify), but either through a configuration option or through a look at the ratio, it could switch to 1?

**Comment by t11r** [comment]
This can already be configured with CSS custom properties, for example:

```css
:root {
   /* width is automatically limited to the panel width, yet percentage values do not work */
   --tify-thumbnail-width: 100vw;
   --tify-thumbnail-height: 3rem;
}
```
