### ISSUE TITLE
Invalid URL params - Reload produces 400 Bad Request

### ISSUE THREAD

**Issue by datazuul** [tify-iiif-viewer/tify#57]
When navigating pages in tify 0.23.0 (and before) the URL is feeded with tify params like this:
http://localhost:10000/view/162330?tify={%22panX%22:0.537,%22panY%22:0.91,%22view%22:%22scan%22,%22zoom%22:0.474}

When clicking reload in browser I get a 400 Bad Request error page.
Server message: 
"Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986"

Seems to be the curly braces, as valid characters are:
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=

**Comment by t11r** [comment]
Thank you for your report!

I agree that according to RFC 3986, `{` and `}` should not be used in URL queries, yet most browsers deliberately send those characters unescaped ([see for example this discussion regarding Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1152455)), and we never encountered any server-side issues with this before.

What browser and server are you using?

**Comment by ipf** [comment]
Seems to be Tomcat. @datazuul could you please try to configure your Tomcat with `System.setProperty("tomcat.util.http.parser.HttpParser.requestTargetAllow", "{}");`

**Comment by datazuul** [comment]
I am using Spring Boot 2.2.6 with embedded Tomcat.

Fixed it by adding

```
server:
  tomcat:
    relaxed-query-chars: "[,],{,}"
    # Comma-separated list of additional unencoded characters that should
    # be allowed in URI query strings. Only "< > [ \ ] ^ ` { | }" are allowed.
```
to the webapps `application.yml`
